const CartActionTypes = {
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
    CLEAR_CART_START: 'CLEAR_CART',
    CLEAR_CART_SUCCESS: 'CLEAR_CART_SUCCESS',
    CLEAR_CART_FAILURE: 'CLEAR_CART_FAILURE',
    UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE',
    PULL_CART_FROM_FIREBASE: 'PULL_CART_FROM_FIREBASE',
}

export default CartActionTypes;